### ISSUE TITLE
Faraday::TimeoutError: request timed out

### ISSUE THREAD

**Issue by kapildewade** [ankane/searchkick#351]
I get this error while reindex the data. Also while making a search request.

using elasticsearch v1.4.2 and latest stable searchkick version. Removing typhoeus worked, but typhoeus is being used in other part of the project. So, any suggestion or alternative to faraday adapter. Not having require adapter/faraday raises "Ethon::Errors::InvalidOption: The option: disable_ssl_peer_verification is invalid." ... To fix this, need faraday and faraday doesnt work with typhoeus.

**Comment by nguyenchiencong** [comment]
+1

**Comment by ankane** [comment]
I created a branch for this, and all tests pass with those versions - https://github.com/ankane/searchkick/tree/typhoeus

Not sure what the problem would be.

**Comment by chrise86** [comment]
Also getting this, any developments?

**Comment by sydneyitguy** [comment]
+1

**Comment by kapildewade** [comment]
@chrise86 / @sydneyitguy .. have you tried with the new branch that @ankane has created recently? or it just doesnt work?

**Comment by sydneyitguy** [comment]
have no idea, but it's just working now.. only thing I did was "curl --help" on command line. lol

**Comment by matthewmoss** [comment]
I am also having this issue. Has any one found a solution?

**Comment by sydneyitguy** [comment]
seems like it's just a slow loading issue with ElasticSearch daemon.
after I upgraded ES to 1.4.2, it loads much slower than before, and having this issue for about 10 seconds after launch (sometimes, it takes much longer like few minutes)

**Comment by iRet** [comment]
Hi guys.
I have two OSX hosts with same configuration and getting this error only on one of them.
Trying to reinstall all gems, upgrading all brew packages, have no idea why it happens.

**Comment by abookyun** [comment]
I ran into the same situation randomly! but fixed it via manually assigning elasticsearch host to `127.0.0.1` rather than default `localhost` in `config/initializers/elasticsearch.rb` as below:

```
Searchkick.client = Elasticsearch::Client.new(hosts: ["127.0.0.1:9200", "127.0.0.1:9201"], retry_on_failure: true)
```

Rails version: 4.1.10
searchkick version: 0.8.7
ES version: 1.5.0

guess it's some kind of localhost loopback issue, hope this helps!

**Comment by iRet** [comment]
I've used tcpdump and saw Faraday trying to connect to IPv6 address, then found in hosts that address bound to localhost and removed. Not sure why, this wasn't a problem for any other software.
So it was solved.

**Comment by kapildewade** [comment]
As it is working for many people with minor config change, i'm closing this issue. I hope @abookyun answer would help.

Thanks all!

**Comment by abookyun** [comment]
thanks all, glad it helps :+1:

**Comment by ankane** [comment]
Cleaning up issues

**Comment by kapildewade** [comment]
Just in case anyone still having problem with typhoeus or faraday,
 Adding below code to config/initializer/elasticsearch.rb

require "faraday"
require "typhoeus/adapters/faraday"
Searchkick.client = Elasticsearch::Client.new(hosts: ["127.0.0.1:9200", "127.0.0.1:9201"], retry_on_failure: true)

fixed this issue for me. Answer taken from #393

**Comment by evanjmg** [comment]
I'm still getting  this error after following the instructions and downgrading to the 'working' versions. I require typhoeus elsewhere in my project (different model). Should I add anything in particular to the typhoeus?

**Comment by nest4less-dev** [comment]
@ankane - Why is this still a problem with Heroku?

**Comment by ankane** [comment]
@nest4less-dev On Heroku, you'll need to point to your Elasticsearch provider, not `127.0.0.1`, which points to your [local machine](https://en.wikipedia.org/wiki/Localhost).
